#! /bin/sh
# GPLv2 - (c) 2013 - Steve Schnepp <steve.schnepp@pwkf.org>
# Rewrite of the original plugin by Bushmills.

# We don't want to care about localized things
LANG=C

pluginfull="$0"                 # full name of plugin
plugin="${0##*/}"               # name of plugin
pidfile="$MUNIN_PLUGSTATE/munin.$plugin.pid"
cache="$MUNIN_PLUGSTATE/munin.$plugin.value"

if [ "$1" = "acquire" ]
then
        (
                while sleep 1
                do
                        awk '
                                BEGIN {
                                        NOW=systime();
                                        HZ=100; # For now 100 is ok
                                }
                                /cpu[0-9]/ {
                                        TOTAL=($2+$3+$4+$5+$6+$7+$8+$9);
                                        printf "%s.value %d:%d\n", $1, NOW, (TOTAL-$5)*100/HZ;
                                }
                                ' < /proc/stat >> $cache
                done
        ) &
        echo $! > $pidfile
        exit 0
fi


if [ "$1" = "config" ]
then
        cat <<EOF
graph_title multicpu1sec
graph_category 1sec::system
graph_vlabel average cpu use %
graph_scale no
graph_total All CPUs
update_rate 1
graph_data_size custom 1d, 10s for 1w, 1m for 1t, 5m for 1y
EOF
for i in $(awk '/^cpu[0-9]/ { print $1 }' /proc/stat)
do
cat << EOF
${i}.label $i
${i}.draw AREASTACK
${i}.type DERIVE
${i}.min 0
EOF
done
        exit 0
fi

# values
cat ${cache}
> ${cache}

exit 0

true <<DATA

/proc/stat
----------
The amount of time, measured in units of USER_HZ (1/100ths of a second on most
architectures, use sysconf(_SC_CLK_TCK) to obtain the right value), that the
system spent in user mode, user mode with low priority (nice), system mode, and
the idle task, respectively.  The last value should be USER_HZ times the second
entry in the uptime pseudo-file.

In Linux 2.6 this line includes three additional columns:
iowait - time waiting for I/O to complete (since 2.5.41)
irq - time servicing interrupts (since 2.6.0-test4)
softirq - time servicing softirqs (since 2.6.0-test4).

Since Linux 2.6.11, there is an eighth column, steal - stolen time, which is
the time spent in other operating systems when running in a virtualized
environment

Since Linux 2.6.24, there is a ninth column, guest, which is the time spent
running a virtual CPU for guest operating systems under the control of the
Linux kernel.

DATA

